services:
  postgres-db:
    image: postgres:16-alpine
    container_name: global-finance-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: global_finance_db
    ports:
      - "5433:5432"
    healthcheck: #  Notifies when the DB is ready
      test: ["CMD-SHELL", "pg_isready -U user -d global_finance_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bank-network

  finance-api:
    build: .
    container_name: global-finance-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/global_finance_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - bank-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Config file
    ports:
      - "9090:9090"
    networks:
      - bank-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password
    networks:
      - bank-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge