name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ] # Active when updating these branches
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Use a Linux server of GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # The robot downloads the code

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Installs Java 21
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw # Give execution permission to the wrapper

      - name: Build and Test with Maven
        run: ./mvnw clean verify # Compiles and executes ALL the tests