//pabloEncoder@finance.com - hi1234
//markgarcia@finance.com - hi1234

### Create a new user
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "name": "",
  "email": "markgarcia-finance.com",
  "password": "hi12"
}

### Login to get the token
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "pabloEncoder@finance.com",
  "password": "hi1234"
}

### Trying to access without token
GET http://localhost:8080/api/users/demo

### Accessing with previous token
GET http://localhost:8080/api/users/demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb0VuY29kZXIzQGZpbmFuY2UuY29tIiwiaWF0IjoxNzY5OTg2MjI2LCJleHAiOjE3NzAwNzI2MjZ9.dD61zHJxqK3shkSkRfJLmEGwUQWRfJoh2agFK7U4J10

### Create a new account (token needed)
POST http://localhost:8080/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJrZ2FyY2lhQGZpbmFuY2UuY29tIiwiaWF0IjoxNzcwNTA3MTk2LCJleHAiOjE3NzA1OTM1OTZ9.zO7rnd-N5t_FCRGF2p9EKVbIgYBC4szGRnDZKdEkcoo
Content-Type: application/json

// pabloEncoder1: ES24-4215-2426-7544-5775-8395 , ES24-9184-7443-9134-5687-5280
// markgarcia: ES24-9524-5642-8238-2843-2358

### See my accounts
GET http://localhost:8080/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb0VuY29kZXJAZmluYW5jZS5jb20iLCJpYXQiOjE3NzA1MTE0ODYsImV4cCI6MTc3MDU5Nzg4Nn0.H03iSddAfilu97H5FE4DC9bjvp3KivAhdTTM3ngaaIo

### Transfer amount of money
POST http://localhost:8080/api/transactions/transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb0VuY29kZXJAZmluYW5jZS5jb20iLCJpYXQiOjE3NzA2NzMwNzYsImV4cCI6MTc3MDc1OTQ3Nn0.dYmscpNB2Kq5JRI5VUvb7a4FqTjciOqUXOGAijXs2TQ
Content-Type: application/json

{
  "sourceAccountNumber": "ES24-4215-2426-7544-5775-8395",
  "targetAccountNumber": "ES24-9524-5642-8238-2843-2358",
  "amount": 15000.00
}

### Deposit Money
POST http://localhost:8080/api/accounts/deposit
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb0VuY29kZXJAZmluYW5jZS5jb20iLCJpYXQiOjE3NzA2NzI2NDksImV4cCI6MTc3MDc1OTA0OX0.h8a0gD2bmUcPrJkmBvIe83WrI0_9U2Rll7OcupqGVXA
Content-Type: application/json

{
  "accountNumber": "ES24-4215-2426-7544-5775-8395",
  "amount": 5000.00
}

### See transactions history
GET http://localhost:8080/api/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYWJsb0VuY29kZXJAZmluYW5jZS5jb20iLCJpYXQiOjE3NzA2NzIyNjcsImV4cCI6MTc3MDc1ODY2N30.KjQwariTu5HQz5QKLut5m4hTrDdHyh4YedLAiwchuts
